name: Actualizacion Automatizada MEF

on:
  schedule:
    # Se ejecuta a las 00:00, 06:00, 12:00 y 18:00 UTC
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente con un clic

permissions:
  contents: write

jobs:
  extract_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar extraccion
        run: python script.py

      - name: Commit y Push de los datos
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data_mef.json
          git commit -m "ðŸ“Š MEF Lambayeque: ActualizaciÃ³n automÃ¡tica $(date)" || echo "Sin cambios"
          git push
